# Generated by Django 2.2.16 on 2022-07-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientAmount',
            new_name='IngridientAmount',
        ),
    ]
