# Generated by Django 2.2.16 on 2022-07-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20220712_0006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingridient',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='IngridientAmount',
            new_name='IngredientAmount',
        ),
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='ingridient',
            new_name='ingredient',
        ),
    ]
